name: rs
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.7.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.4.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.29.0
  - scipy=1.10.1
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.65.0
  - typing_extensions=4.5.0
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - beautifulsoup4==4.12.2
    - bokeh==3.1.1
    - click==8.1.3
    - contourpy==1.1.0
    - cycler==0.11.0
    - decorator==5.1.1
    - deprecated==1.2.14
    - docker-pycreds==0.4.0
    - filelock==3.12.0
    - fonttools==4.40.0
    - future==0.18.3
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - graphtools==1.5.3
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - kmeans-pytorch==0.3
    - m-phate==0.1.6
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - pandas==2.0.2
    - pathtools==0.1.2
    - phate==1.0.10
    - protobuf==4.23.3
    - psutil==5.9.5
    - pygsp==0.5.1
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - s-gd2==1.8.1
    - scikit-learn==1.2.2
    - scprep==1.2.3
    - sentry-sdk==1.25.1
    - setproctitle==1.3.2
    - smmap==5.0.0
    - soupsieve==2.4.1
    - tasklogger==1.2.0
    - threadpoolctl==3.1.0
    - tornado==6.3.2
    - tzdata==2023.3
    - wandb==0.15.4
    - wrapt==1.15.0
    - xyzservices==2023.5.0
    - zipp==3.15.0
